using LSL;
using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;
/// <summary>
/// Adapts in-game data packages and semantic events into LSL-compatible samples.
/// This class should own stream schema decisions and sample formatting, but not
/// session lifecycle policy or LabRecorder TCP commands.
/// </summary>
public class LslDataBridge : IDisposable
{
    private const string DefaultDataStreamPrefix = "NeonatalData";
    private const string MarkerStreamName = "UnityMarkers";

    private StreamInfo markerInfo;
    private StreamOutlet markerOutlet;
    private readonly string[] singleStringSample = new string[1];
    private readonly Dictionary<string, OutletSpec> numericOutlets = new Dictionary<string, OutletSpec>();
    private readonly Dictionary<string, OutletSpec> stringOutlets = new Dictionary<string, OutletSpec>();
    private readonly HashSet<string> schemaWarningsLogged = new HashSet<string>();

    private string cachedParticipantId;
    private string cachedSessionId;
    private string cachedTaskName;
    private string dataStreamPrefix = DefaultDataStreamPrefix;
    private bool includeCollectorNameInStream = true;
    private bool includeScenarioTimeChannel;
    private bool includeSequenceIdChannel;

    private bool isInitialized;

    public void Configure(
        string streamPrefix,
        bool includeCollectorInStreamName,
        bool includeScenarioTimeAsChannel,
        bool includeSequenceIdAsChannel)
    {
        if (isInitialized)
        {
            Debug.LogWarning("LslDataBridge.Configure ignored because streams are already initialized.");
            return;
        }

        dataStreamPrefix = string.IsNullOrWhiteSpace(streamPrefix) ? DefaultDataStreamPrefix : streamPrefix;
        includeCollectorNameInStream = includeCollectorInStreamName;
        includeScenarioTimeChannel = includeScenarioTimeAsChannel;
        includeSequenceIdChannel = includeSequenceIdAsChannel;
    }

    /// <summary>
    /// Initializes all LSL outlets used by this session.
    /// Typical implementation creates one data stream and one marker stream
    /// with stable stream names/source IDs.
    /// </summary>
    /// <param name="sessionId">Unique identifier for this recording session.</param>
    /// <param name="participantId">Participant identifier for metadata.</param>
    /// <param name="taskName">Task/block label for metadata.</param>
    public void InitializeStreams(string sessionId, string participantId, string taskName)
    {
        if (isInitialized)
        {
            return;
        }

        cachedSessionId = string.IsNullOrWhiteSpace(sessionId) ? "unknown-session" : sessionId;
        cachedParticipantId = string.IsNullOrWhiteSpace(participantId) ? "unknown-participant" : participantId;
        cachedTaskName = string.IsNullOrWhiteSpace(taskName) ? "unknown-task" : taskName;

        try
        {
            markerInfo = new StreamInfo(
                MarkerStreamName,
                "Markers",
                1,
                LSL.LSL.IRREGULAR_RATE,
                channel_format_t.cf_string,
                $"{cachedParticipantId}_{cachedSessionId}_{MarkerStreamName}");

            AppendMetadata(markerInfo, cachedParticipantId, cachedSessionId, cachedTaskName);

            markerOutlet = new StreamOutlet(markerInfo);

            isInitialized = true;
            Debug.Log($"Initialized LSL marker stream: {MarkerStreamName}");
            PublishMarker("DataStreamReady", dataStreamPrefix);
        }
        catch (Exception ex)
        {
            Debug.LogError($"Failed to initialize LSL streams: {ex.Message}");
            Dispose();
        }
    }

    /// <summary>
    /// Pushes a structured data package to the LSL data stream.
    /// Recommended approach is one JSON string channel per sample to preserve
    /// mixed data types without numeric conversion.
    /// </summary>
    /// <param name="package">Package generated by a collector/DataLoader.</param>
    public void PublishPackage(DataPackage package)
    {
        if (!isInitialized || package == null)
        {
            return;
        }

        try
        {
            PackageChannelData channels = BuildChannels(package);

            string streamTypeBase = string.IsNullOrWhiteSpace(package.DataType) ? "Unknown" : package.DataType;
            string streamKey = streamTypeBase;
            if (includeCollectorNameInStream)
            {
                string collectorName = string.IsNullOrWhiteSpace(package.CollectorId) ? "unknown_source" : package.CollectorId;
                streamKey = streamTypeBase + "_" + collectorName;
            }

            PublishNumericChannels(streamKey, streamTypeBase, package.CollectorId, channels.NumericNames, channels.NumericValues);
            PublishStringChannels(streamKey, streamTypeBase, package.CollectorId, channels.StringNames, channels.StringValues);
        }
        catch (Exception ex)
        {
            Debug.LogWarning($"Failed to publish package to LSL: {ex.Message}");
        }
    }

    /// <summary>
    /// Pushes a semantic marker event (for example SessionStart, QuizAnswered, SessionStop)
    /// to the LSL marker stream.
    /// </summary>
    /// <param name="markerType">Machine-readable marker category.</param>
    /// <param name="markerValue">Human-readable or JSON marker payload.</param>
    public void PublishMarker(string markerType, string markerValue)
    {
        if (!isInitialized || markerOutlet == null || string.IsNullOrWhiteSpace(markerType))
        {
            return;
        }

        try
        {
            MarkerPayload marker = new MarkerPayload
            {
                Type = markerType,
                Value = markerValue ?? string.Empty,
                UtcIso = DateTime.UtcNow.ToString("O")
            };

            singleStringSample[0] = JsonUtility.ToJson(marker);
            markerOutlet.push_sample(singleStringSample, LSL.LSL.local_clock());
        }
        catch (Exception ex)
        {
            Debug.LogWarning($"Failed to publish marker to LSL: {ex.Message}");
        }
    }

    /// <summary>
    /// Optional hook to force-finalize pending work before teardown.
    /// For pure LSL outlet pushing this may remain a no-op.
    /// </summary>
    public void Flush()
    {
        if (!isInitialized)
        {
            return;
        }

        // Intentionally left as no-op: samples are pushed directly to LSL outlets.
    }

    /// <summary>
    /// Releases outlets and native resources.
    /// Should be safe to call multiple times.
    /// </summary>
    public void Dispose()
    {
        if (!isInitialized && markerOutlet == null && markerInfo == null && numericOutlets.Count == 0 && stringOutlets.Count == 0)
        {
            return;
        }

        try
        {
            DisposeOutletMap(numericOutlets);
            DisposeOutletMap(stringOutlets);
            markerOutlet?.Dispose();
            markerInfo?.Dispose();
        }
        catch (Exception ex)
        {
            Debug.LogWarning($"Error while disposing LSL resources: {ex.Message}");
        }

        markerOutlet = null;
        markerInfo = null;
        numericOutlets.Clear();
        stringOutlets.Clear();
        schemaWarningsLogged.Clear();
        cachedParticipantId = null;
        cachedSessionId = null;
        cachedTaskName = null;

        isInitialized = false;
    }

    private void PublishNumericChannels(string streamKey, string dataType, string collectorId, string[] channelNames, float[] values)
    {
        if (channelNames == null || values == null || channelNames.Length == 0)
        {
            return;
        }

        string streamType = streamKey + "_num";
        OutletSpec spec = GetOrCreateOutlet(stringOutletsMap: null, numericOutletsMap: numericOutlets, streamType: streamType, contentType: dataType, collectorId: collectorId, format: channel_format_t.cf_float32, channelNames: channelNames);
        if (spec == null)
        {
            return;
        }

        Array.Clear(spec.NumericBuffer, 0, spec.NumericBuffer.Length);
        int copyCount = Mathf.Min(values.Length, spec.NumericBuffer.Length);
        for (int i = 0; i < copyCount; i++)
        {
            spec.NumericBuffer[i] = values[i];
        }

        if (values.Length > spec.NumericBuffer.Length)
        {
            LogSchemaWarningOnce(streamType, values.Length, spec.NumericBuffer.Length);
        }

        spec.Outlet.push_sample(spec.NumericBuffer, LSL.LSL.local_clock());
    }

    private void PublishStringChannels(string streamKey, string dataType, string collectorId, string[] channelNames, string[] values)
    {
        if (channelNames == null || values == null || channelNames.Length == 0)
        {
            return;
        }

        string streamType = streamKey + "_str";
        OutletSpec spec = GetOrCreateOutlet(stringOutletsMap: stringOutlets, numericOutletsMap: null, streamType: streamType, contentType: dataType, collectorId: collectorId, format: channel_format_t.cf_string, channelNames: channelNames);
        if (spec == null)
        {
            return;
        }

        for (int i = 0; i < spec.StringBuffer.Length; i++)
        {
            spec.StringBuffer[i] = string.Empty;
        }

        int copyCount = Mathf.Min(values.Length, spec.StringBuffer.Length);
        for (int i = 0; i < copyCount; i++)
        {
            spec.StringBuffer[i] = values[i] ?? string.Empty;
        }

        if (values.Length > spec.StringBuffer.Length)
        {
            LogSchemaWarningOnce(streamType, values.Length, spec.StringBuffer.Length);
        }

        spec.Outlet.push_sample(spec.StringBuffer, LSL.LSL.local_clock());
    }

    private OutletSpec GetOrCreateOutlet(
        Dictionary<string, OutletSpec> stringOutletsMap,
        Dictionary<string, OutletSpec> numericOutletsMap,
        string streamType,
        string contentType,
        string collectorId,
        channel_format_t format,
        string[] channelNames)
    {
        Dictionary<string, OutletSpec> activeMap = format == channel_format_t.cf_string ? stringOutletsMap : numericOutletsMap;
        if (activeMap == null)
        {
            return null;
        }

        if (activeMap.TryGetValue(streamType, out OutletSpec existing))
        {
            if (existing.ChannelCount != channelNames.Length)
            {
                LogSchemaWarningOnce(streamType, channelNames.Length, existing.ChannelCount);
            }

            return existing;
        }

        string streamName = dataStreamPrefix + "." + SanitizeName(streamType);
        string sourceId = string.Format("{0}_{1}_{2}", cachedParticipantId, cachedSessionId, streamName);
        StreamInfo info = new StreamInfo(streamName, string.IsNullOrWhiteSpace(contentType) ? "Unknown" : contentType, channelNames.Length, LSL.LSL.IRREGULAR_RATE, format, sourceId);
        AppendMetadata(info, cachedParticipantId, cachedSessionId, cachedTaskName);
        AppendStreamContextMetadata(info, collectorId, contentType, format == channel_format_t.cf_string ? "string" : "numeric");

        XMLElement desc = info.desc();
        XMLElement channels = desc.append_child("channels");
        for (int i = 0; i < channelNames.Length; i++)
        {
            channels.append_child("channel").append_child_value("label", channelNames[i] ?? ("ch_" + i));
        }

        OutletSpec created = new OutletSpec
        {
            Info = info,
            Outlet = new StreamOutlet(info),
            ChannelCount = channelNames.Length,
            StringBuffer = format == channel_format_t.cf_string ? new string[channelNames.Length] : null,
            NumericBuffer = format == channel_format_t.cf_float32 ? new float[channelNames.Length] : null
        };

        activeMap[streamType] = created;
        Debug.Log("Initialized LSL data stream: " + streamName + " (" + channelNames.Length + " channels)");
        return created;
    }

    private PackageChannelData BuildChannels(DataPackage package)
    {
        List<string> numericNames = new List<string>();
        List<float> numericValues = new List<float>();
        List<string> stringNames = new List<string>();
        List<string> stringValues = new List<string>();

        if (includeSequenceIdChannel)
        {
            numericNames.Add("sequence_id");
            numericValues.Add(package.SequenceId);
        }

        if (includeScenarioTimeChannel)
        {
            stringNames.Add("scenario_time");
            stringValues.Add(package.ScenarioTime ?? string.Empty);
        }

        AppendNamedNumericChannels(numericNames, numericValues, package.NumericChannelNames, package.NumericChannelValues);
        AppendNamedStringChannels(stringNames, stringValues, package.StringChannelNames, package.StringChannelValues);

        if (!string.IsNullOrWhiteSpace(package.PayloadJson))
        {
            stringNames.Add("payload_json");
            stringValues.Add(package.PayloadJson);
        }

        return new PackageChannelData
        {
            NumericNames = numericNames.ToArray(),
            NumericValues = numericValues.ToArray(),
            StringNames = stringNames.ToArray(),
            StringValues = stringValues.ToArray()
        };
    }

    private static void AppendNamedNumericChannels(List<string> names, List<float> values, string[] channelNames, float[] channelValues)
    {
        if (channelNames == null || channelValues == null)
        {
            return;
        }

        int count = Mathf.Min(channelNames.Length, channelValues.Length);
        for (int i = 0; i < count; i++)
        {
            if (string.IsNullOrWhiteSpace(channelNames[i]))
            {
                continue;
            }

            names.Add(channelNames[i]);
            values.Add(channelValues[i]);
        }
    }

    private static void AppendNamedStringChannels(List<string> names, List<string> values, string[] channelNames, string[] channelValues)
    {
        if (channelNames == null || channelValues == null)
        {
            return;
        }

        int count = Mathf.Min(channelNames.Length, channelValues.Length);
        for (int i = 0; i < count; i++)
        {
            if (string.IsNullOrWhiteSpace(channelNames[i]))
            {
                continue;
            }

            names.Add(channelNames[i]);
            values.Add(channelValues[i] ?? string.Empty);
        }
    }

    private static string SanitizeName(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
        {
            return "unknown";
        }

        StringBuilder builder = new StringBuilder(input.Length);
        for (int i = 0; i < input.Length; i++)
        {
            char c = input[i];
            if (char.IsLetterOrDigit(c) || c == '_' || c == '-')
            {
                builder.Append(c);
            }
            else
            {
                builder.Append('_');
            }
        }

        return builder.ToString();
    }

    private void LogSchemaWarningOnce(string streamType, int incomingCount, int expectedCount)
    {
        string key = streamType + "_" + incomingCount + "_" + expectedCount;
        if (schemaWarningsLogged.Contains(key))
        {
            return;
        }

        schemaWarningsLogged.Add(key);
        Debug.LogWarning("LSL stream schema mismatch for " + streamType + ". Incoming channels: " + incomingCount + ", expected: " + expectedCount + ". Data will be truncated/padded.");
    }

    private static void DisposeOutletMap(Dictionary<string, OutletSpec> map)
    {
        foreach (KeyValuePair<string, OutletSpec> kvp in map)
        {
            try
            {
                kvp.Value.Outlet?.Dispose();
                kvp.Value.Info?.Dispose();
            }
            catch
            {
                // Best-effort cleanup.
            }
        }
    }

    private static void AppendMetadata(StreamInfo info, string participantId, string sessionId, string taskName)
    {
        XMLElement desc = info.desc();
        desc.append_child_value("participant_id", participantId);
        desc.append_child_value("session_id", sessionId);
        desc.append_child_value("task_name", taskName);
        desc.append_child_value("unity_version", Application.unityVersion);
        desc.append_child_value("created_utc", DateTime.UtcNow.ToString("O"));
    }

    private static void AppendStreamContextMetadata(StreamInfo info, string collectorId, string dataType, string channelGroup)
    {
        XMLElement desc = info.desc();
        desc.append_child_value("collector_id", string.IsNullOrWhiteSpace(collectorId) ? "unknown" : collectorId);
        desc.append_child_value("data_type", string.IsNullOrWhiteSpace(dataType) ? "Unknown" : dataType);
        desc.append_child_value("channel_group", channelGroup);
    }

    private sealed class OutletSpec
    {
        public StreamInfo Info;
        public StreamOutlet Outlet;
        public int ChannelCount;
        public float[] NumericBuffer;
        public string[] StringBuffer;
    }

    private struct PackageChannelData
    {
        public string[] NumericNames;
        public float[] NumericValues;
        public string[] StringNames;
        public string[] StringValues;
    }

    [Serializable]
    private struct MarkerPayload
    {
        public string Type;
        public string Value;
        public string UtcIso;
    }
}